### ISSUE TITLE
Chapter 1 Content

### ISSUE THREAD

**Issue by Anirach** [FITM-KMUTNB/python-workbook#2]
Chapter 1
Theory - Programming Environment
1.1 Computer System
1.2 Python Language
1.3 Coding Environment
- VsCode
- GitHub
- Hello World
1.4 FlowChart
1.5 UnitTest

LAB - Programming Environment
L 1.1 SetUp
- Coding Environment
- Python
- Hello World
- GitHub
L 1.2 FlowChart
L 1.3 UnitTest

**Comment by n9ti** [comment]
เรื่องเนื้อหาไปคุยต่อกันนี้ issue นี้แทนนะครับ
https://github.com/FITM-KMUTNB/python-workbook/issues/3#issue-434591831
